name: Build and Push to DockerHub

on:
  push:
    branches: ["select-demo"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD:  ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u {Dockeruser} -p {dockerpassword}

    - name: Build the Docker Image
      run: docker build . -t collynb/collyns-dev-portfolio:${{ github.sha }}

    - name: Push Docker Image to DockerHub
      run: docker push collynb/collyns-dev-portfolio:${{ github.sha }}
